name: Deployment
on:
    push:
        branches:
            - main
            - dev
env:
    MONGODB_DB_NAME: gha-demo
jobs:
    test:
        environment: Testing
        runs-on: ubuntu-latest
        # container:
        #  image: node:16
        env:
            MONGODB_CONNECTION_PROTOCOL: mongodb
            MONGODB_PASSWORD: example
            MONGODB_USERNAME: root
            MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017
            PORT: 8080
        services:
            mongodb:
                image: mongo
                ports:
                    - 27017:27017
                env:
                    MONGO_INITDB_ROOT_USERNAME: root
                    MONGO_INITDB_ROOT_PASSWORD: example

        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: npm-deps-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Run server
              run: npm start & npx wait-on http://127.0.0.1:$PORT
            - name: Run tests
              run: npm test
            - name: Output information
              run: |
                  echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME}}"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              run: |
                  echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME}}"
                  echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
